### ISSUE TITLE
Docker image constantly restarting

### ISSUE THREAD

**Issue by lnlyssg** [nanos/FediFetcher#181]
cc'ing @benyafai 

I'm using the below docker-compose to run fedifetcher however I've noticed that it's constantly running, ending and running again within minutes (or even seconds) as per the below screenshot from my Healthchecks instance. It seems that it's not picking up the delay in the restart_policy but I'm not sure why?

<img width="226" alt="Screenshot 2024-10-03 at 09 49 36" src="https://github.com/user-attachments/assets/57f896f3-1048-49eb-9dec-b5dc494f6876">

```
services:
  fedifetcher:
    container_name: fedifetcher
    stdin_open: true
    tty: true
    image: ghcr.io/nanos/fedifetcher:latest
    command: "--access-token=${TOKEN} --server=${SERVER} --config=/app/artifacts/config.json"
    # Persist our data
    volumes:
      - /opt/fedifetcher/:/app/artifacts
    # Use the `deploy` option to enable `restart_policy`
    deploy:
      # Don't go above 1 replica to avoid multiple overlapping executions of the script
      replicas: 1
      restart_policy:
        # The `any` condition means even after successful runs, we'll restart the script
        condition: any
        # Specify how often the script should run - for example; after 1 hour.
        delay: 1h
```
