### ISSUE TITLE
Running from container cannot use config file.

### ISSUE THREAD

**Issue by politas** [nanos/FediFetcher#64]
I have this as a docker-compose file:

```
version: '3'

networks:
  ext_network:

services:
  fetcher:
    image: ghcr.io/nanos/fedifetcher:latest
    container_name: fedifetcher
    restart: always
    command:
      - "-c /app/artifacts/config.json"
    networks:
      - ext_network
    volumes:
      - artifacts:/app/artifacts

volumes:
  artifacts:
    driver_opts:
      type: none
      device: /data/fedifetcher
      o: bind 
```
When I run it, I keep getting this message:

```
fedifetcher  | 2023-07-22 22:24:13.993367 UTC: Starting FediFetcher
fedifetcher  | 2023-07-22 22:24:13.993506 UTC: Config file  /app/artifacts/config.json doesn't exist
fedifetcher exited with code 0
```
The file does exist:

```
$ ls /data/fedifetcher/
config.json
```

I can run the container by including all configuration variables in the "command" block, but I'd rather embed the config file in a locked down volume on the server rather than on my workstation where I keep all my compose files.

**Comment by nanos** [comment]
Hm. I must admit that I’m not really familiar with docker, so other than are you sure you are mounting the correct directory in the correct place, I’m not sure. 

The directory should also contain a lot of artifacts, so the fact that it contains only the config file, is a bit of a red flag.

**Comment by politas** [comment]
When I run with the config specified in the compose file, I get all the artifact files appearing in that folder.

**Comment by th0mcat** [comment]
@politas you'll have to bind mount the config file directly.  Here's my working config:

```
fedifetcher:
    image: ghcr.io/nanos/fedifetcher:latest
    container_name: fedifetcher
    hostname: fedifetcher
...
    command: -c /app/config.json
    volumes:
****      - /opt/fedifetcher/config.json:/app/config.json****
      - /opt/fedifetcher/app/artifacts:/app/artifacts
```

**Comment by politas** [comment]
@th0mcat , Bind mounting the config the same as your setup did not work for me. I still get a `Config file /app/config.json doesn't exist` message.

**Comment by sinful-developer** [comment]
I was able to get the docker-compose file working by changing the command property.
Like this:
```yaml
version: '3'

networks:
  ext_network:

services:
  fetcher:
    image: ghcr.io/nanos/fedifetcher:latest
    container_name: fedifetcher
    restart: always
    command: " -c=/app/artifacts/config.json"
    networks:
      - ext_network
    volumes:
      - artifacts:/app/artifacts

volumes:
  artifacts:
    driver_opts:
      type: none
      device: /opt/test/artifacts
      o: bind
```
The device path on the volume shouldn't have an influence since it's handled by the Docker engine. 
I just changed so it's easier to clean up :P

I don't know why this works, I just saw that the -c flag was defined like this in the readme. 
Maybe Python handles it differently?
